vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        product_image2:
            uri_prefix: /images/products2
            upload_destination: '%kernel.project_dir%/public/images/products2'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            
              # inject_on_load:     false
              # delete_on_update:   true
              # delete_on_remove:   true
    #mappings:
    #    products:
    #        uri_prefix: /images/properties
    #        upload_destination: '%kernel.project_dir%/public/images/products'

